### ISSUE TITLE
[Enhancement] BR2 Performance Issue

### ISSUE THREAD

**Issue by SkylightStudio07** [gulddaggi/Project_BR2#39]
## Description
개발 중 발생한 퍼포먼스 이슈 체크
Unity3D 환경 특성상 GC 과정에서 발생하는 메모리 낭비가 크고, 노트북 환경에서의 정상적인 구현을 위해 최소한의 최적화 작업이 필요

## To-do
- [x] **플레이어 공격 이펙트 오브젝트 풀링.** 
2023-12-08 시점에서 Instantiate-Destroy로 구현되어 있음.
활(Bow) 또한 제한적인 오브젝트 풀링으로 구현되어 있음

- [ ] **남용된 FindObject 계열 함수들 교체**
프로젝트 내 모든 오브젝트를 순환하므로 비용이 큼
- [ ] **문자열은 readonly 혹은 const 키워드를 사용**
GC가 수행되지 않도록...

## ETC
Scene 간 로딩시간은 수행 시간이 오래 걸리는 함수들을 체크하고 집중적으로 최적화 필요. 에디터의 Profiler을 통해 확인 가능
