### ISSUE TITLE
[Feature] New Player Weapon - Bow

### ISSUE THREAD

**Issue by SkylightStudio07** [gulddaggi/Project_BR2#41]
## Description
플레이어 신규 무기 활(Bow) - 무기 태그번호 : 2

## To-do
- [x] **기본적인 뼈대 추가** 
[5da67bc] Player Weapon bow - Alpha 버전 커밋으로 추가 완
- [x] **플레이어 애니메이션 - Bow 추가**
[fe0a4c2] Weapon Change Rework + Bow Alpha V2 커밋으로 불완전하게 추가. 애니메이션 클립 차후 교체 필요
- [x] **플레이어 투사체(화살) 오브젝트 풀**
[fe0a4c2] Weapon Change Rework + Bow Alpha V2 커밋 당시 추가 완료
- [x] **플레이어 투사체(화살) Rotation 보정**
플레이어 투사체의 Rotation이 날아가는 방향으로 보정되지 않는 문제가 현 버전에 존재
- [x] **플레이어 투사체 대미지 설정 및 공격 시스템 설정**

## ETC
차후 버전에 무기를 교체할 경우 오브젝트 풀링이 수행되지 않도록 해야 하는 필요성이 있음

**Comment by SkylightStudio07** [comment]
arrow 프리팹의 rotation은 고쳐졌으나, 아직도 발사되는 방향이 사격때마다 달라짐.
기본적인 토대는 완성되었으므로 develop에 pull 후 추후 재작업 예정.

**Comment by SkylightStudio07** [comment]
로테이션이 꼬이는 문제 해결 불가. Instantiate - Destroy로 수행해도 하등 퍼포먼스 문제는 없으므로 오브젝트 풀링 제거.
이제 투사체는 정상적으로 대미지를 입힘.
