### ISSUE TITLE
[Feature] Effect when enemy attacked(stiffness, VFX)

### ISSUE THREAD

**Issue by SkylightStudio07** [gulddaggi/Project_BR2#43]
## Description
적 피격시 VFX 및 경직 추가. 디버그 용도로도 적합함

## To-do
- [x] **적 피격시 VFX 추가** 
추가적인 에셋이 필요할 수 있음
- [x] **적 피격시 경직 추가**
추가적인 애니메이션 클립이 필요할 수 있음
- [x] **Enemy 스크립트들 전반적인 리팩토링 및 상속 재정립 필요**

**Comment by SkylightStudio07** [comment]
feature/enhance-battle 브랜치에서 HitEffectManager.cs 실장으로 적 피격 이펙트 구현 완료
