### ISSUE TITLE
[Bug/Feature] special attack guage bug / new Special Attacks

### ISSUE THREAD

**Issue by SkylightStudio07** [gulddaggi/Project_BR2#67]
## Description
현재 원거리 공격 무기(활/수리검)은 정상적으로 작동하나 특수공격 게이지가 쌓이지 않는 문제가 있음.
또한 두 무기 전부 특수공격이 실장되지 않은 상태임.

## To-do
- [x] **Bug : Special Attack Guage** 
[72778f3] 해당 커밋 당시 특수공격 게이지 버그가 발생.
- [x] **활(무기 태그번호 : 2) 특수공격 실장**
수리검의 하위호환적 감각 및 광범위 타격 개념으로 -30, 0. 30 각도로 화살을 전탄발사
- [x] **수리검(무기 태그번호 : 3) 특수공격 실장**
활의 상위호환적 감각 및 단일 대상 누킹 개념으로 0.2초 간격으로 수리검을 발사

## ETC
현재 원거리 무기들의 단일 공격력이 지나치게 강력함. 구울이 평타 2방에 즉사할 정도.
이에 따라 화살은 몰라도 수리검은 공격력에 너프를 가해야 할 필요성이 보임.

**Comment by SkylightStudio07** [comment]
[3c95c06] 커밋으로 버그 픽싱 및 새로운 특수 공격 실장 완료
